---
title: "About"
output: 
  md_document:
    df_print:
      "kable"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = 'markdown')
```

# À propos

Cette application a été développée pour produire des estimations des dates d'exposition pour les cas d'Ebola. Elle peut également produire des estimations de la date à laquelle les symptômes se sont développés si nous avons des informations sur les symptômes ou la date de décès.

Auteurs:

* Katy Gaythorpe a développé l'application.

* Aaron Morris a développé l'analyse de cluster.

* Mary Choi a développé la logique de la calculatrice.

* Miles Stewart a développé la version de l'application VHF.

* Mara Kont aidé à la traduction.

Les commentaires et demandes pour l'application doivent être envoyés à k.gaythorpe AT imperial.ac.uk ou aaron.morris10 AT imperial.ac.uk

## Version portable/de bureau de chainchecker compatible avec la base de données VHF

Est disponible depuis le référentiel GitHub sur https://github.com/imperialebola2018/chainchecker/releases

## Citation

Gaythorpe, KAM et Morris, A. et Imai, N. et Stewart, M. et Freeman, J. et Choi M. "chainchecker", 2019, [https://shiny.dide.imperial.ac.uk/chainchecker/ ]