---
title: "About"
output: 
  md_document:
    df_print:
      "kable"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = 'markdown')
```

# About

This app was developed to produce estimates of exposure dates for Ebola cases. It can also produce estimates of the date that symptoms developed if we have information on symptoms or date of death.

Authors: 

* Katy Gaythorpe developed the app. 

* Aaron Morris developed the cluster analysis.

* Mary Choi developed the calculator logic.

* Miles Stewart developed the VHF app version. 

* Mara Kont helped with the translation.

Feedback and requests for the app should be sent to k.gaythorpe AT imperial.ac.uk or aaron.morris10 AT imperial.ac.uk

## Desktop/ portable chainchecker for use with VHF database

Is available form the GitHub repository at https://github.com/imperialebola2018/chainchecker/releases 

## Citation

Gaythorpe, K. A. M. and Morris, A. and Imai, N. and Stewart, M. and Freeman, J. and Choi M. "chainchecker", 2019, [https://shiny.dide.imperial.ac.uk/chainchecker/] 